# -*- coding: utf-8 -*-
"""
OLED Monitor 시스템 상수
"""

# 디스플레이 설정
OLED_WIDTH = 128
OLED_HEIGHT = 64
OLED_PAGES = 8
BYTES_PER_PAGE = 128

# 통신 설정
SERIAL_BAUDRATE = 921600  # 기본 통신속도를 921600으로 변경
SERIAL_TIMEOUT = 1.0
COMMAND_TIMEOUT = 2000
RESPONSE_TIMEOUT = 3000

# 지원 가능한 통신속도 목록
SUPPORTED_BAUDRATES = [
    9600,
    19200,
    38400,
    57600,
    115200,
    230400,
    460800,
    921600
]

# 프로토콜 명령어 (펌웨어 호환)
COMMANDS = {
    'SCREEN_REQUEST': b'GET_SCREEN\n',
    'STATUS_REQUEST': b'GET_STATUS\n',
    'PING': b'PING\n',
    'RESET': b'RESET\n',
    'TIMER_START': b'TIMER_START\n',
    'TIMER_STOP': b'TIMER_STOP\n',
    'TIMER_SET': b'TIMER_SET:{}\n',
}

# 응답 패턴
RESPONSE_PATTERNS = {
    'SCREEN_START': b'SCREEN_START',
    'SCREEN_END': b'SCREEN_END',
    'STATUS_START': b'STATUS:',
    'STATUS_END': b'\n',
    'PONG': b'PONG',
    'OK': b'OK',
    'ERROR': b'ERROR',
}

# 상태 값
STATUS_VALUES = {
    'STANDBY': 'STANDBY',
    'RUNNING': 'RUNNING',
    'SETTING': 'SETTING',
    'COOLING': 'COOLING',
    'ERROR': 'ERROR',
    'UNKNOWN': 'UNKNOWN',
}

# 배터리 관련
BATTERY_MIN = 0
BATTERY_MAX = 5000
BATTERY_ADC_MIN = 0
BATTERY_ADC_MAX = 4095

# 로그 레벨
LOG_LEVELS = {
    'DEBUG': 0,
    'INFO': 1,
    'WARNING': 2,
    'ERROR': 3,
    'CRITICAL': 4,
}

# 파일 경로
DEFAULT_LOG_DIR = "LOG"
DEFAULT_GRAPHS_DIR = "graphs"
DEFAULT_RUN_DIR = "run"

# 성능 설정
DEFAULT_REFRESH_INTERVAL = 100  # ms
MAX_BUFFER_SIZE = 1000
PARSING_TIMEOUT = 5  # seconds

# 이미지 처리
DEFAULT_SCALE = 4
MIN_SCALE = 1
MAX_SCALE = 10
BORDER_WIDTH = 2
BORDER_COLOR = 128 